Makes missing runtime more clear

diff --git a/routr b/routr
--- a/routr
+++ b/routr
@@ -29,6 +29,6 @@ if running_in_docker ; then
   [ -z "$ROUTR_LOCALNETS" ] && export ROUTR_LOCALNETS=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}')
 fi
 
-[ -z "$JAVA_HOME" ] && { echo "Could not find a runtime environment"; exit 1; }
+[ -z "$JAVA_HOME" ] && { echo "Could not find a runtime environment. Please setup environment variable JAVA_HOME"; exit 1; }
 
 run
