Simplified

diff --git a/routr b/routr
--- a/routr
+++ b/routr
@@ -1,15 +1,13 @@
 #!/usr/bin/env sh
 
-[ ! -z "$JAVA_HOME" ] && VM_HOME=$JAVA_HOME
-[ ! -z "$GRAALVM_HOME" ] && VM_HOME=$GRAALVM_HOME
-[ ! -z "$CUSTOM_RUNTIME" ] && VM_HOME=$CUSTOM_RUNTIME
+# Ensure Java is at least 8
 
 running_in_docker() {
   [ -f /proc/self/cgroup ] && awk -F/ '$2 == "docker"' /proc/self/cgroup | read
 }
 
 run() {
-  $1/bin/java \
+  $JAVA_HOME/bin/java \
     -Dlog4j.configurationFile=config/log4j2.xml \
     $ROUTR_JAVA_OPTS \
     -classpath "libs/*" \
@@ -21,6 +19,6 @@ if running_in_docker ; then
   [ -z "$ROUTR_LOCALNETS" ] && export ROUTR_LOCALNETS=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}');
 fi
 
-[ -z "$VM_HOME" ] && { echo "Could not find a runtime environment"; exit 1; }
+[ -z "$JAVA_HOME" ] && { echo "Could not find a runtime environment"; exit 1; }
 
-run $VM_HOME
+run
